spring.thymeleaf.cache=false
spring.web.resources.chain.cache=false

shadleaf.dev.vite-server-url=http://localhost:5174
shadleaf.dev.templates-path=../../shadleaf-spring-boot-starter/src/main/resources/templates/

vite.mode=dev
