import fs from 'node:fs';
import path from 'node:path';

/*
  Generates one CSS entry point per skin x asset variant into css/entries/, so adding a skin is adding
  a file to css/skins/ and adding a component is adding a file to css/components/.

  - standalone: the whole of Tailwind (preflight included) plus the page base styles, for applications
    that do not compile Tailwind themselves.
  - embedded:   no preflight and no page base styles, for applications that compile Tailwind and own the
    base layer. theme(inline) compiles Tailwind's theme values into the rules instead of emitting
    --spacing, --text-sm, ... into the shared theme layer, where they would override the application's own.
    utilities.css is still imported because @apply needs it; with source(none) it emits nothing.

  Called from vite.config.js, so `vite` and `vite build` always see up-to-date entries.
*/

export const VARIANTS = {
  standalone: {
    suffix: '',
    tailwind: ['@import "tailwindcss" source(none);'],
    page: true
  },
  embedded: {
    suffix: '.embedded',
    tailwind: [
      '@layer theme, base, components, utilities;',
      '@import "tailwindcss/theme.css" layer(theme) theme(inline);',
      '@import "tailwindcss/utilities.css" layer(utilities) source(none);'
    ],
    page: false
  }
};

// Components whose selectors compose come in this order; any others follow alphabetically.
const COMPONENT_ORDER = ['base', 'button'];

export function generateCssEntries(cssDir) {
  const skins = cssFileNames(path.join(cssDir, 'skins')).sort();
  const components = orderComponents(cssFileNames(path.join(cssDir, 'components')));
  if (!skins.includes('default')) {
    throw new Error(`There must be a skins/default.css, found: ${skins.join(', ')}`);
  }

  const entriesDir = path.join(cssDir, 'entries');
  fs.mkdirSync(entriesDir, {recursive: true});

  const inputs = {};
  const expectedFiles = new Set();
  for (const skin of skins) {
    for (const [variantName, variant] of Object.entries(VARIANTS)) {
      const fileName = `shadleaf-${skin}${variant.suffix}.css`;
      const content = [
        `/* GENERATED by scripts/css-entries.js: skin '${skin}', ${variantName}. Do not edit. */`,
        ...variant.tailwind,
        '',
        '@import "../tokens.css";',
        ...(variant.page ? ['@import "../page.css";'] : []),
        ...components.map(name => `@import "../components/${name}.css";`),
        `@import "../skins/${skin}.css";`,
        ''
      ].join('\n');
      const filePath = path.join(entriesDir, fileName);
      writeIfChanged(filePath, content);
      expectedFiles.add(fileName);
      inputs[path.basename(fileName, '.css')] = filePath;
    }
  }

  // A removed skin must not leave a stale entry behind.
  for (const file of fs.readdirSync(entriesDir)) {
    if (!expectedFiles.has(file)) {
      fs.rmSync(path.join(entriesDir, file));
    }
  }
  return inputs;
}

function cssFileNames(dir) {
  return fs.readdirSync(dir)
      .filter(file => file.endsWith('.css'))
      .map(file => path.basename(file, '.css'));
}

function orderComponents(names) {
  const known = COMPONENT_ORDER.filter(name => names.includes(name));
  const others = names.filter(name => !COMPONENT_ORDER.includes(name)).sort();
  return [...known, ...others];
}

function writeIfChanged(filePath, content) {
  if (!fs.existsSync(filePath) || fs.readFileSync(filePath, 'utf8') !== content) {
    fs.writeFileSync(filePath, content);
  }
}
