package io.github.wimdeblauwe.shadleaf.icon;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import org.jspecify.annotations.Nullable;
import tools.jackson.databind.json.JsonMapper;

/**
 * The lucide icons bundled in the jar ({@code shadleaf/icons/lucide.json}, generated from the lucide-static package
 * by {@code scripts/icons.js}), including lucide's aliases for renamed icons.
 * <p>
 * The catalogue is read on first use, so an application that never renders an icon never loads it.
 */
public class LucideIconSource implements IconSource {

  public static final String CATALOGUE_LOCATION = "shadleaf/icons/lucide.json";

  private final JsonMapper jsonMapper;
  private volatile @Nullable Catalogue catalogue;

  public LucideIconSource(JsonMapper jsonMapper) {
    this.jsonMapper = jsonMapper;
  }

  @Override
  public Optional<Icon> find(String name) {
    Catalogue catalogue = catalogue();
    String body = catalogue.icons().get(catalogue.aliases().getOrDefault(name, name));
    return Optional.ofNullable(body).map(Icon::lucide);
  }

  @Override
  public Set<String> names() {
    return catalogue().icons().keySet();
  }

  /** The version of lucide-static the catalogue was generated from. */
  public String version() {
    return catalogue().version();
  }

  private Catalogue catalogue() {
    Catalogue loaded = catalogue;
    if (loaded == null) {
      synchronized (this) {
        loaded = catalogue;
        if (loaded == null) {
          loaded = load();
          catalogue = loaded;
        }
      }
    }
    return loaded;
  }

  private Catalogue load() {
    try (InputStream inputStream = LucideIconSource.class.getClassLoader().getResourceAsStream(CATALOGUE_LOCATION)) {
      if (inputStream == null) {
        throw new IllegalStateException(CATALOGUE_LOCATION + " is missing from the classpath. It is generated by "
            + "scripts/icons.js during the Maven build (pnpm run build).");
      }
      return jsonMapper.readValue(inputStream, Catalogue.class);
    } catch (IOException e) {
      throw new UncheckedIOException("Could not read " + CATALOGUE_LOCATION, e);
    }
  }

  record Catalogue(String version, Map<String, String> icons, Map<String, String> aliases) {

  }
}
